patch:
  schema_list:
    - {schema: luna_pinyin}
    - {schema: luna_pinyin_simp}
    - {schema: double_pinyin_flypy}
    - {schema: jyutping}
  switcher:
    caption: "[方案選單]"
    hotkeys:
      - "Control+F1"
  menu/page_size: 5
  ascii_composer:
    good_old_caps_lock: true
    switch_key:
      Caps_Lock: noop
      Shift_L: commit_code
      Shift_R: noop
      Control_L: noop
      Control_R: noop
  punctuator:
    import_preset: alternative
