# luna_pinyin_tw.custom.yaml

patch:
  # 載入朙月拼音擴充詞庫
  translator/dictionary: luna_pinyin.extended
  # 改寫拼寫運算，使得含西文的詞彙（位於 luna_pinyin.cn_en.dict.yaml 中）不影響簡拼功能（注意，此功能只適用於朙月拼音系列方案，不適用於各類雙拼方案）
  "speller/algebra/@before 0": xform/^([b-df-np-z])$/$1_/

  # Emoji
  engine/translators:
    - punct_translator
    - r10n_translator
    - reverse_lookup_translator
  recognizer/patterns/reverse_lookup: "`[a-z]*$"
  schema/dependencies:
    - emoji
  abc_segmentor/extra_tags:
    - reverse_lookup
  reverse_lookup:
    dictionary: emoji
    enable_completion: false
    prefix: "`"
    tips: 〔表情〕
