var:
  option:
    ascii_punct: true
    full_shape: false
    simplification: false
  previously_selected_schema: double_pinyin_flypy
  schema_access_time:
    double_pinyin_flypy: 1475287621
    jyutping: 1427943098
    luna_pinyin: 1475284508
    luna_pinyin_simp: 1475287244
    luna_pinyin_tw: 1475284844