customization:
  distribution_code_name: Weasel
  distribution_version: 0.9.30
  generator: "Weasel::UIStyleSettings"
  modified_time: "Sat Oct 01 08:20:21 2016"
  rime_version: 1.1.2
patch:
  app_options:
    atom.exe:
      ascii_mode: true
    code.exe:
      ascii_mode: true
    conemu.exe:
      ascii_mode: true
    conemu64.exe:
      ascii_mode: true
    explorer.exe:
      ascii_mode: true
    lingoes.exe:
      ascii_mode: true
    listary.exe:
      ascii_mode: true
    mintty.exe:
      ascii_mode: true
    subl.exe:
      ascii_mode: true
    sublime_text.exe:
      ascii_mode: true
  style:
    color_scheme: dark_temple
    display_tray_icon: true
    font_point: 14
    horizontal: false
    inline_preedit: false
